### ISSUE TITLE
Call to undefined method ReflectionMethod::getAttributes() Koriym.NullObject/src/NullObject.php:88

### ISSUE THREAD

**Issue by NaokiTsuchiya** [koriym/Koriym.NullObject#2]
ReflectionMethod::getAttributes() is available starting with 8.0 PHP version.

Please run `demo/run.php` of the following repo with 7.4, 7.3.
https://github.com/NaokiTsuchiya/Koriym.NullObject/tree/getAttributes

Message is here.

```
PHP Fatal error:  Uncaught Error: Call to undefined method ReflectionMethod::getAttributes() in /Users/tsuchiya/work/tsuchiya/Koriym.NullObject/src/NullObject.php:88
Stack trace:
#0 /Users/tsuchiya/work/tsuchiya/Koriym.NullObject/src/NullObject.php(75): Koriym\NullObject\NullObject->getMethodMeta(Object(ReflectionMethod))
#1 /Users/tsuchiya/work/tsuchiya/Koriym.NullObject/src/NullObject.php(57): Koriym\NullObject\NullObject->getMethods('Demo\\FooInterfa...')
#2 /Users/tsuchiya/work/tsuchiya/Koriym.NullObject/autoloader.php(28): Koriym\NullObject\NullObject->__invoke('Demo\\FooInterfa...')
#3 [internal function]: {closure}('Demo\\FooInterfa...')
#4 /Users/tsuchiya/work/tsuchiya/Koriym.NullObject/demo/run.php(15): spl_autoload_call('Demo\\FooInterfa...')
#5 {main}
  thrown in /Users/tsuchiya/work/tsuchiya/Koriym.NullObject/src/NullObject.php on line 88

Fatal error: Uncaught Error: Call to undefined method ReflectionMethod::getAttributes() in /Users/tsuchiya/work/tsuchiya/Koriym.NullObject/src/NullObject.php:88
Stack trace:
#0 /Users/tsuchiya/work/tsuchiya/Koriym.NullObject/src/NullObject.php(75): Koriym\NullObject\NullObject->getMethodMeta(Object(ReflectionMethod))
#1 /Users/tsuchiya/work/tsuchiya/Koriym.NullObject/src/NullObject.php(57): Koriym\NullObject\NullObject->getMethods('Demo\\FooInterfa...')
#2 /Users/tsuchiya/work/tsuchiya/Koriym.NullObject/autoloader.php(28): Koriym\NullObject\NullObject->__invoke('Demo\\FooInterfa...')
#3 [internal function]: {closure}('Demo\\FooInterfa...')
#4 /Users/tsuchiya/work/tsuchiya/Koriym.NullObject/demo/run.php(15): spl_autoload_call('Demo\\FooInterfa...')
#5 {main}
  thrown in /Users/tsuchiya/work/tsuchiya/Koriym.NullObject/src/NullObject.php on line 88
```

**Comment by koriym** [comment]
Will be fixed soon. Currently working on only PHP 8.0.
I will add `.github` CI support when it's ready.

**Comment by koriym** [comment]
@NaokiTsuchiya Now working on PHP 7.3, 7.4 and 8.0!
https://github.com/koriym/Koriym.NullObject/actions?query=workflow%3A%22Continuous+Integration%22
